Implemented SuccessPage and routing for form submission
zealmaster/anti-robot-user-form pull request #3
Opened 2024-08-13 13:29 UTC by Palakmeena

I request a thorough review as I want to avoid any issues that might arise from merging this without proper validation.

2024-08-13 13:54 UTC, zealmaster commented on src/components/SuccessPage.tsx
Move the ccs styles to index.css

2024-08-13 14:12 UTC, zealmaster commented on src/index.tsx
Remove the components import

2024-08-13 14:12 UTC, zealmaster commented on src/components/SuccessPage.tsx
Move the ccs styles to App.css

2024-08-13 14:15 UTC, zealmaster requested changes
Move the ccs styles to App.css
Remove the components import

2024-08-13 22:32 UTC, Palakmeena commented
I completed the redirecting part , please review it

2024-08-14 07:02 UTC, zealmaster approved these changes

2024-08-14 08:39 UTC, Mo-wo approved these changes

2024-08-14 09:11 UTC, merged